spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Parul-Geete/config-server.git
          cloneOnStart: true
          default-label: main
server:
  port: 8888


